version: 2
jobs:
  build:
    docker:
      - image: circleci/node:chakracore-8.10.0
    working_directory: ~/workspace
    steps:
      - checkout

      - restore_cache:
          keys:
            - deps-v1-{{ checksum "yarn.lock" }}

      - run:
          name: Install Dependencies
          command: make install-no-clean

      - save_cache:
          paths:
            - node_modules
          key: deps-v1-{{ checksum "yarn.lock" }}

      - run:
          name: Lint
          command: make lint
          when: always

      - run:
          name: Package functions
          command: make package
          when: always

      - store_artifacts:
          path: artifacts

      - persist_to_workspace:
          root: ./
          paths:
            - artifacts/
            - node_modules/

  deploy:
    docker:
      - image: circleci/node:chakracore-8.10.0
    working_directory: ~/workspace
    steps:
      - checkout

      - attach_workspace:
          at: ~/workspace

      - run:
          name: Install Deployment Dependencies
          command: make install-deployment-deps

      - run:
          name: Deploy Production
          command: STAGE=dev make deploy

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: convert-to-app
